
#region Copyright SHARP Corporation
//	Copyright (c) 2010-2014 SHARP CORPORATION. All rights reserved.
//
//	Extended Sharp OSA SDK
//
//	This software is protected under the Copyright Laws of the United States,
//	Title 17 USC, by the Berne Convention, and the copyright laws of other
//	countries.
//
//	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ``AS IS'' AND ANY EXPRESS 
//	OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//	OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
//
//==============================================================================
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace GetJob
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-sc-jp:mfp:osa-1-1", IsNullable = false)]
    public partial class result
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GetJobSettableElementsResponse")]
        public GetJobSettableElementsResponse JobSettableElementsResponse;
 
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-sc-jp:mfp:osa-1-1", IsNullable = false)]
    public partial class GetJobSettableElementsResponse
    {              

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("xml-doc-out")]
        public Xmldocout xmldocout;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string generic;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("product-family")]
        public string productfamily;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("product-version")]
        public string productversion;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("operation-version")]
        public string operationversion;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    public partial class Xmldocout
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("fileId")]
        public string fileId;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("device-info")]
        public Deviceinfo deviceinfo;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("meta-element")]
        public Metadata metadata;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("complex")]
        public complex[] complex;

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    public partial class Deviceinfo
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serial-number")]
        public string serialnumber;

        /// <remarks/>
        public string modelname;

        /// <remarks/>
        public string location;

        /// <remarks/>
        public string mac_address;

        /// <remarks/>
        public string network_address;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    public partial class Metadata
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sys-name")]
        public string sysname;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-sc-jp:mfp:osa-1-1", IsNullable = false)]
    public partial class complex
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property")]
        public Property[] property;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sys-name")]
        public string sysname;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isType;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minOccurs;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxOccurs;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    public partial class Property
    {

        /// <remarks/>
        public string value;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("hasConstraint", typeof(PropertyAppInfo))]
        public PropertyAppInfo[] appInfo;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("allowed", typeof(string))]
        public string[] allowedValueList;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sys-name")]
        public string sysname;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string isType;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minOccurs;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxOccurs;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    public partial class PropertyAppInfo
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }

}