
#region Copyright SHARP Corporation
//	Copyright (c) 2010-2014 SHARP CORPORATION. All rights reserved.
//
//	Extended Sharp OSA SDK
//
//	This software is protected under the Copyright Laws of the United States,
//	Title 17 USC, by the Berne Convention, and the copyright laws of other
//	countries.
//
//	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ``AS IS'' AND ANY EXPRESS 
//	OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
//	OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
//
//==============================================================================
#endregion
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace SetJob
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-sc-jp:mfp:osa-1-1", IsNullable = false)]
    public partial class complex
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property", IsNullable = true)]
        public Property[] property;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sys-name")]
        public string sysname;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    public partial class Property
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sys-name")]
        public string sysname;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-sc-jp:mfp:osa-1-1", IsNullable = false)]
    public partial class SetJobElements
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("JobId")]
        public SetJobElementsJobId[] JobId;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("config-data")]
        [System.Xml.Serialization.XmlArrayItemAttribute("complex", typeof(complex), IsNullable = false)]
        public complex[] complex;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string generic;
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-sc-jp:mfp:osa-1-1")]
    public partial class SetJobElementsJobId
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("job-type")]
        public string jobtype;

        /// <remarks/>
        public string UISessionId;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uid;
    }
}