/// <summary>
/// E_EA_MESSAGE_TYPE
/// </summary>
public enum E_EA_MESSAGE_TYPE
{
    OSA_SCAN_TROUBLE = 1,
    OSA_PRINT_ENG_TROUBLE = 2,
    OSA_PRINT_ENG_FEEDSYSTEM_TROUBLE = 3,
    OSA_PRINT_ENG_TRANSPORTSYSTEM_TROUBLE = 4,
    OSA_SYSTEM_TROUBLE = 5,
    OSA_LIMITS_REACHED = 6,
    OSA_CONTROL_SYSTEM_TROUBLE = 7,
    OSA_PROCESS_CONTROL_TROUBLE = 8,
    OSA_TONER_TROUBLE = 9,
    OSA_DEVELOPER_TROUBLE = 10,
    OSA_OPTIONS_TROUBLE = 11,
    OSA_NETWORK_TROUBLE = 12,
    OSA_FAX_TROUBLE = 13,
    OSA_RIC_TROUBLE = 14,
    OSA_FATAL_ERROR_OTHER = 15,
    OSA_SCAN_ORG_JAM = 16,
    OSA_PRINT_PAPER_JAM = 17,
    OSA_SCAN_ORG_NOTDETECTED = 18,
    OSA_PRINT_FEEDTRAY = 19,
    OSA_PRINT_OUTTRAY_FULL = 20,
    OSA_OPERATIONAL_ERROR_OTHER = 21,
    OSA_PRINT_TONER_LOW = 22,
    OSA_PRINT_PAPER_LOW = 23,
    OSA_PRINT_OUTTRAY_NOTEMPTY = 24,
    OSA_PRINT_STAPLE = 25,
    OSA_SERVICE_REQUIRED_TROUBLE = 26,
    OSA_WARNING_OTHER = 27,
    OSA_SYS_READY = 28,
    OSA_SYS_DOOR_OPEN = 29,
    OSA_INFO_OTHER = 30,
    SIMPLEEA_OTHER = 31,
    SIMPLEEA_LOGINERROR = 32,
    SIMPLEEA_SYSERROR = 33,
    // 2012.06.13 Add by Wei Changye 
    SIMPLEEA_REGISTER_LIMIT=34,
    //end
}
