//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36470
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomAction.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomAction.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 USE [master]
        ///
        ////****** Object:  Database [SimpleEA] ******/
        ///IF  EXISTS (SELECT name FROM sys.databases WHERE name = N&apos;SimpleEA&apos;)
        ///DROP DATABASE [SimpleEA]
        ///GO
        ///
        ///GO
        ////****** Object:  Database [SimpleEA] ******/
        ///CREATE DATABASE [SimpleEA]
        ///
        ///GO
        ///IF (1 = FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        ///begin
        ///EXEC [SimpleEA].[dbo].[sp_fulltext_database] @action = &apos;enable&apos;
        ///end
        ///GO
        ///ALTER DATABASE [SimpleEA] SET ANSI_NULL_DEFAULT OFF 
        ///GO
        ///ALTER DATABASE [SimpleEA] SET ANSI_NULLS OFF 
        ///GO
        ///ALTER DATABASE [S [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Create_database {
            get {
                return ResourceManager.GetString("Create_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*****************************************************************************/
        ////* System           : SIMPLE EA SYSTEM DB CREATE                             */
        ////* Name             : DB CREATE SCRIPT                                       */
        ////* Description      :                                                        */
        ////* Author &amp; Date    : SES  2010/07/08                                        */
        ////* Update           : SES JiJianxiong 2010/11/12                             */
        ////* Notes            :      [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Update_database {
            get {
                return ResourceManager.GetString("Update_database", resourceCulture);
            }
        }
    }
}
